metadata_files:
  - resources/2021_metadata.csv
  - resources/2022_metadata.csv
  - resources/2023_metadata.csv

output_folder: results

columns_to_rename:
  old_column_name: new_column_name

latitude_column: latitude
longitude_column: longitude
sample_name_column: sample_id

geographical_hierarchy:
  - 

spellcheck_geography:
  2-10:
    old_entry: new_entry

  coordinate_fixes:
    collection_site_header: HF_NAME
    