metadata_files:
  - resources/2021_metadata.csv
  - resources/2022_metadata.csv
  - resources/2023_metadata.csv

output_folder: results

columns_to_rename:
  old_column_name: new_column_name
  COLLECTION_YEAR: YEAR_COLLECTED
  RDT_RESULT: MRDT_RESULTS
  LONGTUDE: LONGITUDE
  YEAR_COLLECTION: YEAR_COLLECTED
  
latitude_column: latitude
longitude_column: longitude
sample_name_column: sample_id

geographical_hierarchy:
  - region
  - region_code
  - district
  - district_code
  - hfname
  - hf_code

spellcheck_geography:
  5-50:
    old entry: new entry
  4308-4311:
    BKG: RWB
  3134-3170:
    Bukoba Dc: Bukoba
  3180-3382:
    Bukoba_rural: Bukoba
  12167-12367:
    MU: MS
  8283-8389:
    Lyamungu: Lyamungo
  20995-21455:
    Mamboleo-community: Mamboleo
  20582-20886:
    Magoda-community: Magoda
  21544-21929:
    Mpapayu-community: Mpapayu
  7059-7857:
    Nyankoroko-community: Nyankoroko
  15692-15728:
    MAK: MAKB
  19645-19844:
    Nzega Tc: Nzega
  14641-14843:
    Newala Tc: Newala
  9315-9352:
    MWG: MWGA
  7858-8024:
    Nyankoronko: Nyankoroko
  12972-13007:
    NYA: NYAM
  3171-3179:
    Bukoba Dc: Bukoba
  2-75:
    IL: ILA
  19245-19281:
    KA: KAL
  2402-2440:
    KG: KGA
  10033-10968:
    KI: KIT
  12368-12405:
    MU: MUS
  4750-5594:
    MU: MUL
  13587-13640:
    MU: MTW